### ISSUE TITLE
photo settings

### ISSUE THREAD

**Issue by alecini** [fo-am/waspsurvey#28]
As they are, the photo panels do not look really nice: is there's a way to put them in a nicer way, say for example a grid..etc?
Otherwise,m suggestions to make this part looking professional? probably choosing always the same size? which would be the right size?

**Comment by nebogeo** [comment]
I've made the site automatically resize the images so they all have the same fixed width (270 pixels) - so you don't need to make them all the same resolution, but the problem is the aspect ratio (ratio of width to height) which I can't change without distorting the images. To fix that, you'll need to crop them so the height is always the same ratio to the width - it doesn't matter what this is, as long as it's consistent, so they don't jumble up the layout.

The other issue is the backgrounds are all different, so it looks a bit messy - but without actually taking all the photos in a controlled manner or cutting out all the insects (which would look bad in a different way) I think it will be ok with the aspect ratio fix.

**Comment by alecini** [comment]
OK, sounds nice, we can do that.
You're totally right about different backgrounds, but there's no way to standardized this, and also,the same background such as a museum specimen would be misleading as well and unrealistic, so let's put the photo we can put our hand on!
I'll check the ratio, thanks
