### ISSUE TITLE
selecting videos

### ISSUE THREAD

**Issue by alecini** [fo-am/waspsurvey#44]
Currently both videos are about predation. I'm missing the "how to upload a video" and then "how to select a video".
I thought it was like the images section...what am I missing? maybe it is through youtube, but I cannot see how we can do that.
what would be nice to have: as for insect photos, possibility to upload video on the survey manager, name them and then call them in the question.

**Comment by nebogeo** [comment]
The video files were out of date, I'm uploading them now - there isn't a way to do this via the admin. We serve them from our server rather than YouTube - mainly to avoid advertising and all the stuff that comes with that. You can specify the videos just via "predation" or "pollination" in the choices box.
